version: '3.8'
services:
  app-one:
    image: dockerswarmexample-app-one
    ports:
      - "5001:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  app-two:
    image: dockerswarmexample-app-two
    ports:
      - "5002:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    restart: on-failure
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
